### ISSUE TITLE
Allow for more than one tests to be added in this project

### ISSUE THREAD

**Issue by dance-cmdr** [oodlefinance/front-end-technical-test#3]
Good work to begin with.

I think it would be nice to use the main README.md as an index page and link to the challenges that live within the sub-directories.

Vote Up, if you want me to act on this one or Vote Down if you want me to close it.

**Comment by remyoudemans** [comment]
Interesting. Why do you think there should be more than one technical test?

**Comment by dance-cmdr** [comment]
We can have tests that focus on different aspects of the frontend: project building, styling, UX, algorithms, problem-solving.

**Comment by remyoudemans** [comment]
Of course we can, but should we? If yes, why?

**Comment by dance-cmdr** [comment]
I'm not aware of the previous conversation, so I'm just expressing my opinion without knowledge of prior agreements. So bear with me if I say things that have been shot down before.

I have formed a few beliefs regarding interviews and coding challenges:

- New hires complement a team; therefore, the team must have formed an opinion on what they are looking for.
- A candidate then must be interviewed by members of the team.
- One test doesn't cover all the bases. (Biased Personal Opinion Alert! ) When I read a CV, I want to challenge particular skills and drill on those skills during the face to face interview. Therefore, I would like to have access to a collection of tests to challenge the candidate on different craft aspects.
- The tests must be relevant to the product that the candidate will be working on. (That way, the candidate tastes what they are going to do. It's better to be dropped by a candidate during the interview stage than losing him 6 months later because they didn't like the subject.)
- The more open the test, the more probable the candidate will go blank because they couldn't decide what to do. We might test decision making on purpose, of course. I expect a junior to lose a lot of time wandering, so I would avoid testing junior developers with an open problem.

BTW, is this something you have agreed on passing on, at least for the next few candidates?

**Comment by dance-cmdr** [comment]
I don't care about rotating the tests if a candidate prepares for it; kudos!

**Comment by remyoudemans** [comment]
hey @oodlefinance/web-engineering-guild what do you think?

**Comment by remyoudemans** [comment]
In [this guild meeting](https://oodlefinance.atlassian.net/wiki/spaces/WEBENG/pages/2404188208/10+02+2021+-+Guild+meeting) we decided (as in it's listed in the decisions at the bottom) that there should be just one technical test. That said, it's not written in stone, there's definitely room for discussion.

**Comment by nova93** [comment]
A single test could test a variety of skills, as well as the devs preference.

Example: I am more comfortable with data manipulation, rather than CSS animations or SVG manipulation. My fork of this test would clearly show that. I'd imagine a dev who's more visually/design focused, would produce a completely different app.

If a test gives an option for the dev to fully explore their preference or strongest side, it would mean we don't need multiple tests.

I agree with @dance-cmdr that a new team member should be complementing the team they are joining. We know that it didn't work this way previously, however this would be a good time to correct that.
I also agree with the importance of the test being relevant to the product they'll be working on, however it could be argued that the technical test is not stand-alone, and that the product would be explained before we send the technical test, in which case this point is moot.
I'd counter Alex's point on open tests for juniors. I think IC1-2 shouldn't be required to do a tech test at all. At that point, their problem-solving skills, and ability to learn is what is important.

**Comment by dance-cmdr** [comment]
We did that. I'm closing it.
