### ISSUE TITLE
Tests Should be Oodle branded

### ISSUE THREAD

**Issue by dance-cmdr** [oodlefinance/front-end-technical-test#4]
Amazing job, guys!

I agree that a TODO list is a good challenge; however, I believe it is the easiest to fake. Another problem is that it says absolutely nothing about Oodle's context.

I recommend designing tests that are more relevant to Oodle.
One example would be to make a form with validation, hints, an active/inactive submit button, and several Custom UI elements that filters a collection of cars.

For extra points, we can ask to invent a solution on how we can make all these fields reactive. I mean, how can you change the range of PCM instalments without making all the rest of the form invalid>

Vote Up if you want me to act on this one or Vote Down if you want me to close it.

**Comment by remyoudemans** [comment]
Hey @dance-cmdr! 

> I agree that a TODO list is a good challenge; however, I believe it is the easiest to fake. Another problem is that it says absolutely nothing about Oodle's context.

It took me a while to figure out why you thought we were considering a TODO list. The TODO in the README is just because it hasn't been finished yet 😛 . The actual test I've been working on is in this PR: 
https://github.com/oodlefinance/front-end-technical-test/pull/1

I guess the rest of your points would fit in as comments on that PR.

**Comment by dance-cmdr** [comment]
Fair enough!
